version: 2
updates:
  # Enable version updates for Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "00:00"
    open-pull-requests-limit: 3
    reviewers:
      - "lazureykis"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      # Group all minor and patch updates into a single PR
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "00:00"
    open-pull-requests-limit: 2
    reviewers:
      - "lazureykis"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      # Group all minor and patch updates into a single PR
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"