[package]
name = "throttlecrab"
version = "0.1.0"
edition = "2024"
authors = ["Pavel Lazureykis <pavel@lazureykis.dev>"]
description = "A high-performance GCRA (Generic Cell Rate Algorithm) rate limiter"
readme = "README.md"
repository = "https://github.com/lazureykis/throttlecrab"
license = "MIT OR Apache-2.0"
keywords = ["rate-limiter", "gcra", "throttle", "rate-limiting", "async"]
categories = ["algorithms", "asynchronous", "network-programming"]

[dependencies]
